apiVersion: v1
kind: Service
metadata:
  name: muleexampcleservice
#  namespace: my-namespace
  labels:
    component: muleexampcleservice
    service: muleexampcleservice
spec:
  type: NodePort
  selector:
    name: muleexample-selector
  ports:
  - name: http
    port: 8080 
    targetPort: 8080
    nodePort: 30030 
    protocol: TCP
